
slide:
	jupyter nbconvert Klopfenstein-2018.ipynb --to slides --post serve

# resize:
# 	convert BookImmunology.jpg -resize 50 BookImmunology50.png

# Copyright (C) 2016-2019, DV Klopfenstein. All rights reserved.
