
slide:
	jupyter nbconvert Klopfenstein-2018.ipynb --to slides --post serve

# resize:
# 	convert BookImmunology.jpg -resize 50 BookImmunology50.png

# Notes:
# https://medium.com/learning-machine-learning/present-your-data-science-projects-with-jupyter-slides-75f20735eb0f
# https://medium.freecodecamp.org/how-to-build-interactive-presentations-with-jupyter-notebook-and-reveal-js-c7e24f4bd9c5
# https://stackoverflow.com/questions/6558740/css-image-size   (css with div)
# https://www.w3schools.com/Css/css_positioning.asp
# https://stackoverflow.com/questions/37743144/how-to-increase-the-page-width-in-ipython-notebook-jupyter-slides
# https://www.htmlgoodies.com/beyond/css/article.php/3470391/So-You-Want-Positioning-Huh.htm#an
# https://stackoverflow.com/questions/32370281/how-to-embed-image-or-picture-in-jupyter-notebook-either-from-a-local-machine-o


# Copyright (C) 2016-2019, DV Klopfenstein. All rights reserved.
